version: "3"
services:
  postgres1:
    image: postgres:15.1
    restart: always
    volumes: 
      - db1:/var/lib/postgresql/data
      - ./db/threads.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - "7432:5432"
    network_mode: host
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: foo@foo.foo
      PGADMIN_DEFAULT_PASSWORD: bar
    network_mode: host
volumes:
  db1:
    driver: local
