version: "3"
services:
  api-1:
    build: 
      context: ./subgraph-1
    volumes:
      - ./subgraph-1:/api
    environment:
      NODE_ENV: development
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@localhost:5432/postgres 
      PORT: 8000
    ports: ['9080:8000'] 
    network_mode: host